version: '3.8'

services:
  # Aplikasi Utama Laravel + Apache Terintegrasi
  app:
    image: webdevops/php-apache:8.4
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/html/public
      - WEB_DOCUMENT_INDEX=index.php
    ports:
      - "8082:80" # Pintu masuk utama HTTP
    volumes:
      - cake_src:/var/www/html
    depends_on:
      - mysql
      - redis
    networks:
      - cake-network
      - dokploy-network

  # WhatsApp Service
  wa-service:
    build: ./wa-service
    ports:
      - "3005:3000"
    volumes:
      - wa-session:/app/.wwebjs_auth
    networks:
      - cake-network

  # Redis
  redis:
    image: redis:7-alpine
    networks:
     - cake-network

  # Horizon (Queue Worker Laravel)
  horizon:
    image: webdevops/php-apache:8.4
    command: php artisan horizon
    depends_on:
      - redis
      - mysql
    volumes:
      - cake_src:/var/www/html
    networks:
      - cake-network

  # MySQL Database
  mysql:
    image: mysql:8.0
    command: --default-time-zone='+07:00'
    environment:
      MYSQL_DATABASE: cake_shop
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: cake_user
      MYSQL_PASSWORD: cake_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - cake-network

volumes:
  mysql_data:
  wa-session:
  cake_src:

networks:
  cake-network:
    driver: overlay
    attachable: true
  dokploy-network:
    external: true
